package de.unibi.cebitec.bibigrid.util;

import com.jcraft.jsch.JSch;
import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.KeyPair;
import java.io.ByteArrayOutputStream;

/**
 *  Generates a public/private KeyPair.
 * 
 * @author Jan Krueger - jkrueger(at)cebitec.uni-bielefeld.de
 */
public class KEYPAIR {

    private String privateKey;
    private String publicKey;

    public KEYPAIR() throws JSchException {
        JSch ssh = new JSch();
        KeyPair kpair = KeyPair.genKeyPair(ssh, KeyPair.RSA);
        ByteArrayOutputStream bao = new ByteArrayOutputStream();
        kpair.writePrivateKey(bao);
        privateKey = bao.toString();
        bao = new ByteArrayOutputStream();
        kpair.writePublicKey(bao, "generated by BiBiGrid");
        publicKey = bao.toString();
    }

    public String getPrivateKey() {
        return privateKey;
    }

    public String getPublicKey() {
        return publicKey;
    }

}
