version: '3.5'
services:
  bibigrid:
    image: bibiserv/bibigrid:${BIBIGRID_TAG}

    ports:
      - ${BIBIGRID_PORT}:${BIBIGRID_PORT}

    env_file:
      - .tmp.env

    volumes:
      - ${HOME}/.bibigrid:/root/.bibigrid

    # Higher priority than values in .env
    environment:
      - OS_AUTH_URL
      - OS_PROJECT_ID
      - OS_PROJECT_NAME
      - OS_USERNAME
      - OS_PASSWORD
      - OS_USER_DOMAIN_NAME
      - OS_PROJECT_DOMAIN_ID
      - OS_PROJECT_DOMAIN_NAME
      - BIBIGRID_TAG

