- debug:
    msg: 
    - "Hello {{ ansible_user }}!"

- name: Unarchive ZIP file from GitHub repository
  unarchive:
    src: "https://github.com/deNBI/bibigrid_clum/raw/main/resources/Resistance_Nextflow.tar.xz"
    dest: "/vol/spool/"
    remote_src: yes

- name: Install Java JRE on Debian/Ubuntu
  become: True
  apt:
    name: default-jre
    state: present

- name: Get Nextflow
  shell: wget -qO- https://get.nextflow.io | bash
  args:
    chdir: /vol/spool/

- name: Change file ownership, group and permissions
  file:
    path: /vol/spool/nextflow
    owner: ubuntu
    group: ubuntu
    mode: '0775'

#- name: Execute Nextflow workflow
#  become_user: ubuntu
#  shell: ./nextflow run resFinder.nf -profile slurm # run your workflow
#  args:
#    chdir: "/vol/spool"  # Change to the directory where your workflow resides
