package de.unibi.cebitec.bibigrid.core.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Host configuration for the ansible scripts.
 * <p/>
 * The {@link #toString() toString} method outputs the configuration in ini format
 * ready to use for ansible.
 *
 * @author mfriedrichs(at)techfak.uni-bielefeld.de
 */
public class AnsibleHostsConfig {
    private static final String PYTHON_INTERPRETER = "ansible_python_interpreter=/usr/bin/python3";
    private final String sshUser;
    private final List<String> workerIps;
    private final List<String> hostnames;
    private final boolean useHostnames;

    AnsibleHostsConfig(String sshUser, List<Instance> workerInstances, boolean useHostnames) {
        this.sshUser = sshUser;
        this.useHostnames = useHostnames;
        workerIps = new ArrayList<>();
        hostnames = new ArrayList<>();
        for (Instance instance : workerInstances) {
            hostnames.add(instance.getHostname());
            workerIps.add(instance.getPrivateIp());
        }
    }

    @Override
    public String toString() {
        StringBuilder hostsConfig = new StringBuilder();
        hostsConfig.append("# The content of this file (ansible_hosts) should be generated by ");
        hostsConfig.append("BiBiGrid during instance initialization.\n");
        hostsConfig.append("# Depending on the used base image the ansible_user must be changed. ");
        if (useHostnames) {
            hostsConfig.append("Using 'useHostnames' in configuration, the hostname of each worker must\n");
        } else {
            hostsConfig.append("The local ip address of each worker must\n");
        }
        hostsConfig.append("# be inserted in the worker section\n\n");
        hostsConfig.append("[master]\n");
        hostsConfig.append("localhost ansible_connection=local " + PYTHON_INTERPRETER + "\n\n");
        hostsConfig.append("[workers]\n");
        if (useHostnames) {
            for (String hostname : hostnames) {
                hostsConfig.append(hostname).append(" ansible_connection=ssh " + PYTHON_INTERPRETER + " ansible_user=");
                hostsConfig.append(sshUser).append("\n");
            }
        } else {
            for (String workerIp : workerIps) {
                hostsConfig.append(workerIp).append(" ansible_connection=ssh " + PYTHON_INTERPRETER + " ansible_user=");
                hostsConfig.append(sshUser).append("\n");
            }
        }
        return hostsConfig.toString();
    }
}
