- name: slurmdbd
  systemd:
    name: slurmdbd
    state: restarted

- name: slurmrestd
  systemd:
    name: slurmrestd
    state: restarted
    daemon_reload: yes

- name: slurmctld
  systemd:
    name: slurmctld
    state: restarted

- name: slurmd
  systemd:
    name: slurmd
    state: restarted