#!/bin/bash

# if CLASSPATH variable is set then append bibigrid-full.jar to it and call
# main class directly, otherwise call like before

if [ -z "$CLASSPATH" ]; then
	java $JVM_OPTS -jar `dirname $0`/bibigrid-java-full.jar $@
else
	CLASSPATH=$CLASSPATH:`dirname $0`/bibigrid-java-full.jar
	java $JVM_OPTS de.unibi.cebitec.bibigrid.StartUpOgeCluster $@
fi
