FROM python:3.12-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements files into the container
COPY pyproject.toml .
COPY uv.lock .

RUN apt-get update && apt-get install -y openssh-client gcc

# Install the dependencies listed in the pyproject.toml with rest dependencies
RUN pip install '.[rest]'

# Install SSH keygen

# Copy the application code into the container
COPY . .

# Make the script executable
RUN chmod +x bibigrid_rest.sh

# Expose port 8080 for the REST API
EXPOSE 8080

# Run the command to start the REST API when the container is launched
CMD ["./bibigrid_rest.sh"]

