FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements files into the container
COPY requirements-rest.txt .
COPY requirements.txt .

# Install the dependencies listed in the requirements files
RUN pip install -r requirements-rest.txt
RUN pip install -r requirements.txt

# Install SSH keygen
RUN apt-get update && apt-get install -y openssh-client

# Copy the application code into the container
COPY . .

# Make the script executable
RUN chmod +x bibigrid_rest.sh

# Expose port 8080 for the REST API
EXPOSE 8080

# Run the command to start the REST API when the container is launched
CMD ["./bibigrid_rest.sh"]
