[project]
name = "bibigrid"
version = "3.1.0"
description = "BiBiGrid is a cloud cluster creation and management tool."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pysocks",
    "ipdb",
    "click",
    "openstacksdk==4.8.0",
    "mergedeep",
    "paramiko<4.0.0",
    "python-cinderclient",
    "python-keystoneclient",
    "python-novaclient",
    "python-openstackclient",
    "shortuuid",
    "sshtunnel",
    "sympy",
    "seedir",
    "pydantic",
    "filelock",
    "schema",
    "Werkzeug"
]

[project.optional-dependencies]
rest = [
    "fastapi",
    "uvicorn"
]
dev = [
    "ansible",
    "ansible_lint==25.9.0",
    "pylint",
    "httpx"
]

[tool.uv]
environments = ["platform_system != 'Windows'"]

[project.scripts]
bibigrid = "bibigrid.core.startup:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["bibigrid*",]
exclude = ["tests*"]

[tool.setuptools.package-data]
"bibigrid.resources" = ["**/*"]
