galaxy_info:
  role_name: Hello-World Example
  author: Tim Dilger
  description: Shows working example of installing Ansible Role.
  company: Bielefeld university, CeBiTec, BiBiServ

  license: BSD

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - stretch
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - hello-world

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
