# -*- mode: ruby -*-
# vi: set ft=ruby :


$masterscript = <<MASTER
apt-get update
echo "Install and configure bind on master"
bash /vagrant/vagrant/bind.sh
echo "Update resolve.conf"
bash /vagrant/vagrant/resolv.sh
echo "Install ansible"
bash /vagrant/vagrant/ansible.sh
echo "Copy ssh keys for passwordless internal ssh connection"
bash /vagrant/vagrant/ssh.sh
MASTER

$workerscript = <<WORKER
echo "Update resolve.conf"
bash /vagrant/vagrant/resolv.sh
echo "Copy ssh keys for passwordless internal ssh connection"
bash /vagrant/vagrant/ssh.sh
WORKER

Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/xenial64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.provision "shell",
        inline: $masterscript,
        run: "always"
    master.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
    end

  end

  config.vm.define "client1" do |client1|
    client1.vm.box = "ubuntu/xenial64"
    client1.vm.hostname = "client1"
    client1.vm.network "private_network", ip: "192.168.33.11"
    client1.vm.provision "shell",
        inline: $workerscript,
        run: "always"
    client1.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
    end
  end

end
