- name: Create /vol/scratch bind mount from /mnt ephemeral
  mount:
    path: /vol/scratch
    src: /mnt
    fstype: none
    opts: bind,auto
    state: mounted
  when:
    - ephemerals
    
- name: Change permissions for /vol/scratch mount point
  file:
    path: /vol/scratch
    state: directory
    mode: 0777
  when:
    - ephemerals
