# we have to make sure that the disk is NOT mounted by cloud-init beforehand
- name: mount disk
  mount:
    path: /vol/scratch
    src: "{{ ephemerals[0] }}"
    fstype: ext4
    state: mounted
  when:
    - ephemerals
    
- name: Change permission for newly mounted /vol/scratch mount point
  file:
    path: /vol/scratch
    state: directory
    mode: 0777
  when:
    - ephemerals
