- debug:
    msg: "[BIBIGRID] Setup Apache and Ganglia monitor"
- include: 001-monitor.yml

- debug:
    msg: "[BIBIGRID] Mount disk"
- include: 005-disk.yml

- debug:
    msg: "[BIBIGRID] Setup NFS"
  when:
    - enable_nfs == 'yes'
- include: 010-nfs.yml
  when: enable_nfs == 'yes'

- debug:
    msg: "[BIBIGRID] Setup GridEngine"
  when:
    - enable_gridengine == 'yes'
- include: 020-gridengine.yml
  when:
    - enable_gridengine == 'yes'

- debug:
    msg: "[BIBIGRID] Setup Slurm Worker"
  when: enable_slurm == 'yes'
- include: 021-slurm.yml
  tags: ['slurm']
  when: enable_slurm == 'yes'

- debug:
    msg: "[BIBIGRID] Setup Mesos"
  when:
    - enable_mesos == 'yes'
- include: 030-mesos.yml
  when: enable_mesos == 'yes'
