- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Get my public IP
  community.general.ipify_facts:
  register: public_ip

- name: Create wg0.conf file
  template:
    src: wireguard/wg0.jinja
    dest: /etc/wireguard/wg0.conf
    owner: ubuntu
    group: ubuntu

- name: Reload WireGuard Configuration
  when: "'wg0' in ansible_interfaces"
  become: yes
  shell:
    cmd: "wg syncconf wg0 <(wg-quick strip wg0)"

- name: Up WireGuard
  when: "'wg0' not in ansible_interfaces"
  shell:
    cmd: wg-quick up wg0
  ignore_errors: true

# Currently automatically done by wireguard
# - name: Allow ip forwarding
#   sysctl:
#     name: net.ipv4.ip_forward
#     value: 1
#     sysctl_set: true
#     state: present
#     reload: true
#   when: "ansible_distribution_file_variety == 'Debian'"