- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Get my public IP
  community.general.ipify_facts:
  register: public_ip

- name: Create wg0.conf file
  template:
    src: wireguard/wg0.jinja
    dest: /etc/wireguard/wg0.conf
    owner: ubuntu
    group: ubuntu

#- name: Up WireGuard
#  shell:
#    cmd: wg-quick up wg0

# Currently automatically done by wireguard
# - name: Allow ip forwarding
#   sysctl:
#     name: net.ipv4.ip_forward
#     value: 1
#     sysctl_set: true
#     state: present
#     reload: true
#   when: "ansible_distribution_file_variety == 'Debian'"