- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Get my public IP
  community.general.ipify_facts:
  register: public_ip

- name: Setup wg0 device
  template:
    src: wireguard/device.jinja
    dest: /etc/systemd/network/wg0.netdev
    owner: root
    group: systemd-network
    mode: 0640
  become: yes
  notify:
    - systemd-networkd restart

- name: Setup wg0 network
  template:
    src: wireguard/network.jinja
    dest: /etc/systemd/network/wg0.network
    owner: root
    group: systemd-network
    mode: 0640
  become: yes
  notify: systemd-networkd restart
