- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Disable and Stop systemd-resolve
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Remove /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Create /etc/hosts
  template:
    src: dns/hosts.j2
    dest: /etc/dnsmasq.hosts
    mode: "0o644"
  notify: Dnsmasq

- name: Adjust dnsmasq.resolv.conf
  template:
    src: dns/resolv.conf.j2
    dest: /etc/dnsmasq.resolv.conf
    mode: "0o644"
  notify: Dnsmasq

- name: Adjust dnsmasq conf
  template:
    src: dns/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: "0o644"
  notify: Dnsmasq

- name: Flush handlers
  meta: flush_handlers
