- name: Ensure zabbix user exists
  when: "'master' not in group_names"
  user:
    name: zabbix
    comment: "Zabbix Monitoring User"
    home: /var/lib/zabbix
    shell: /usr/sbin/nologin
    create_home: false

- name: Create zabbix_agent dropin directory
  file:
    path: /etc/zabbix/zabbix_agentd.d/
    state: directory
    mode: "0o755"

- name: Create zabbix_agent log directory
  file:
    path: /var/log/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: "0o755"

- name: Adjust zabbix agent2 configuration
  template:
    src: zabbix/zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    mode: "0o644"
  notify: Zabbix-agent2

- name: Copy Zabbix Host delete script
  copy:
    src: zabbix/zabbix_host_delete.py
    dest: /usr/local/bin/zabbix_host_delete.py
    mode: "0o755"

- name: Install zabbix agent2
  apt:
    name: zabbix-agent2
    state: present
  when: "ansible_distribution_file_variety == 'Debian'"

- name: Install zabbix agent
  dnf:
    name: zabbix-agent
    state: present
  when: "ansible_distribution_file_variety == 'RedHat'"

- name: Start and Enable zabbix-agent2
  systemd:
    name: zabbix-agent2
    state: started
    enabled: true

# --------------------------------------
# -- Add worker node as zabbix hosts --
# --------------------------------------

- name: Add worker node to zabbix hosts
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_http_use_ssl: false
    ansible_user: Admin
    ansible_httpapi_pass: "{{ zabbix_conf.admin_password }}"
  zabbix_host:
    host_name: "{{ ansible_hostname }}"
    visible_name: "{{ ansible_hostname }}"
    description: add by ansible
    status: enabled
    state: present
    host_groups:
      - 'Linux servers'
    link_templates:
      - 'Linux by Zabbix Agent'
    interfaces:
      - type: 1 # agent
        main: 1 # default
        ip: "{{ ansible_default_ipv4.address }}"
        useip: 1 # connect using host IP address
        port: 10050
  become: false
  when: "'master' not in group_names"
  delegate_to: localhost

# --------------------------------------
# -- Add master node as zabbix hosts --
# --------------------------------------

- name: Add master node to zabbix hosts
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_http_use_ssl: false
    ansible_user: Admin
    ansible_httpapi_pass: "{{ zabbix_conf.admin_password }}"
  zabbix_host:
    host_name: "{{ ansible_hostname }}"
    visible_name: "{{ ansible_hostname }}"
    description: add by ansible
    status: enabled
    state: present
    host_groups:
      - 'Linux servers'
    link_templates:
      - 'Linux by Zabbix Agent'
    interfaces:
      - type: 1 # agent
        main: 1 # default
        ip: "127.0.0.1"
        useip: 1 # connect using host IP address
        port: 10050
  become: false
  when: "'master' in group_names"
