- name: Generate directory structure available on all hosts
  file:
    path: /etc/bibigrid
    state: directory
    owner: root
    group: '{{ ansible_distribution | lower }}'
    mode: "0o775"

- name: Create /vol/ directory with rights 0775 owned by root
  file:
    path: /vol/
    state: directory
    owner: root
    group: '{{ ansible_distribution | lower }}'
    mode: "0o775"

- name: Create /vol/spool/ directory with rights 0777
  file:
    path: /vol/spool/
    state: directory
    mode: "0o777"

- name: Change rights of /opt directory to 0775 and set group to ansible_distribution
  file:
    path: /opt
    state: directory
    owner: root
    group: '{{ ansible_distribution | lower }}'
    mode: "0o775"

- name: Create link in '{{ ansible_distribution | lower }}' home
  file:
    src: /vol/
    dest: '/home/{{ ansible_distribution | lower }}/vol'
    state: link

- name: Automount
  when: volumes is defined
  include_tasks: 020-disk-automount.yaml
  with_items: "{{ volumes }}"
