- name: Install NFS common package
  apt:
    name: "nfs-common"
    state: present

- name: Wait for nfs-server available
  wait_for:
    host: "{{ '10.0.0.1' if wireguard is defined else master.private_v4 }}"
    port: 2049
    delay: 2
    state: started

- name: Create mount points
  file:
    path: "{{ item.dst }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items:
    - "{{ nfs_mounts }}"

- name: Mount shares
  mount:
    path: "{{ item.dst }}"
    src: "{{ '10.0.0.1' if wireguard is defined else master.private_v4 }}:{{ item.src }}"
    fstype: nfs4
    state: mounted
  with_items:
    - "{{ nfs_mounts }}"
