- name: Install Docker
  apt:
    name:
      - docker.io
      - python3-docker
      - docker-compose
      - docker-compose-v2
    state: present
  tags: install

- name: Configure Docker
  copy:
    content: |-
      {
         "mtu":{{ ansible_default_ipv4.mtu }}
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0o644"
  notify:
    Docker

- name: Create docker group and change GID
  group:
    name: docker
    gid: 1234
    state: present

- name: Append ubuntu user to group docker
  user:
    name: ubuntu
    append: true
    groups: docker

- name: (Re-)start docker socket
  systemd:
    name: docker.socket
    state: restarted
