- name: Create Slurm group
  group:
    name: slurm
    gid: 64030

- name: Create Slurm user
  user:
    name: slurm
    uid: 64030
    group: slurm

- name: Install Slurm package (and dependencies)
  apt:
    name:
      - slurm-full
      - munge
      - libjwt0
    state: latest

- name: Create new secret (Munge)
  copy:
    content: '{{ slurm_conf.munge_key }}'
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0600
  notify:
    - munge

- name: Ensures slurm directories exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: root
    group: slurm
  with_items:
    - /etc/slurm
    - /var/lib/slurm
    - /var/log/slurm

- name: Create system overrides directories (slurmd, slurmctld)
  file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    group: root
    owner: root
    mode: "0755"
    state: directory
  with_items:
    - slurmd
    - slurmctld

- name: Copy system overrides (slurmd, slurmctld)
  copy:
    src: "slurm/systemd/{{ item }}.override"
    dest: "/etc/systemd/system/{{ item }}.service.d/override.conf"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - slurmd
    - slurmctld
  notify:
    - slurmd
    - slurmctld

- name: Enable slurmctld and slurmd services
  systemd:
    name: "{{item}}"
    enabled: true
    masked: no
    state: started
    daemon_reload: true
  with_items:
  - slurmctld
  - slurmd

- name: Create Slurm configuration
  template:
    src: slurm/slurm.conf
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: root
    mode: 0444
  notify:
    - slurmctld
    - slurmd

- name: Slurm cgroup configuration
  copy:
    src: slurm/cgroup.conf
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: root
    mode: 0444
  notify:
    - slurmctld
    - slurmd
