- name: Install Slurm base packages and dependencies
  apt:
    name:
      - slurm-wlm
      - munge

- name: Create new secret (Munge)
  copy:
    content: '{{ slurm_conf.munge_key }}'
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0600
  notify:
    - munge

- name: Disable slurmctld (on worker)
  systemd:
    name: slurmctld
    enabled: false
  when: "'master' not in group_names"

- name: SLURM configuration
  template:
    src: slurm/slurm.conf
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: root
    mode: 0444
  notify:
    - slurmctld
    - slurmd

- name: SLURM cgroup configuration
  copy:
    src: slurm/cgroup.conf
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: root
    mode: 0444
  notify:
    - slurmctld
    - slurmd

- name: SLURM cgroup allowed devices conf
  copy:
    src: slurm/cgroup_allowed_devices_file.conf
    dest: /etc/slurm/cgroup_allowed_devices_file.conf
    owner: root
    group: root
    mode: 0444
  notify:
    - slurmctld
    - slurmd
