- name: Create Slurm group
  group:
    name: slurm
    gid: 64030

- name: Create Slurm user
  user:
    name: slurm
    uid: 64030
    group: slurm

#- name: Create pinning configuration for slurm-bibigrid version 23.11.*
#  copy:
#    content: |
#      Package: slurm-bibigrid
#      Pin: version 23.11.*
#      Pin-Priority: 1001
#    dest: /etc/apt/preferences.d/slurm-bibigrid
#    mode: "0o311"

- name: Install slurm-bibigrid package
  apt:
    name: slurm-bibigrid-24.11
    state: present

- name: Install Slurm package dependencies
  apt:
    name:
      - munge

- name: Create new secret (Munge)
  copy:
    content: '{{ slurm_conf.munge_key }}'
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: "0o600"
  notify:
    - Munge

- name: Ensures slurm directories exists
  file:
    path: "{{ item }}"
    state: directory
    mode: "0o775"
    owner: root
    group: slurm
  with_items:
    - /etc/slurm
    - /var/lib/slurm
    - /var/log/slurm

- name: Create system overrides directories (slurmd, slurmctld)
  file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    group: root
    owner: root
    mode: "0o755"
    state: directory
  with_items:
    - slurmd
    - slurmctld

- name: Copy system overrides (slurmd, slurmctld)
  copy:
    src: "slurm/systemd/{{ item }}.override"
    dest: "/etc/systemd/system/{{ item }}.service.d/override.conf"
    mode: "0o644"
    owner: root
    group: root
  with_items:
    - slurmd
    - slurmctld

- name: Enable slurmctld and slurmd services
  systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: started
    daemon_reload: true
  with_items:
    - slurmctld
    - slurmd

- name: Create Slurm configuration
  template:
    src: slurm/slurm.j2
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: root
    mode: "0o444"

- name: Create Job Container configuration
  template:
    src: slurm/job_container.j2
    dest: /etc/slurm/job_container.conf
    owner: slurm
    group: root
    mode: "0o444"

- name: Slurm cgroup configuration
  copy:
    src: slurm/cgroup.conf
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: root
    mode: "0o444"

- name: Restart slurmd
  systemd:
    name: slurmd
    state: restarted
