---
- hosts: all
  become: yes
  tasks:
   - name: restart ssh
     service:
        name: ssh
        state: restarted

   - name: restart ganglia monitor
     service:
        name: ganglia-monitor
        state: restarted

- hosts: master
  become: yes
  tasks:
   - name: restart gmetad
     service:
        name: gmetad
        state: restarted