- name: Assure existence of ansible group
  group:
    name: ansible
    state: present

- name: Change mode of /opt/slurm directory
  file:
    group: ansible
    path: /opt/playbook/
    state: directory
    recurse: true
    mode: "0o770"
