- name: Enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: Enable tcp mtu probing
  sysctl:
    name: net.ipv4.tcp_mtu_probing
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Setup wg0 device
  template:
    src: wireguard/device.j2
    dest: /etc/systemd/network/wg0.netdev
    owner: root
    group: systemd-network
    mode: "0o640"
  become: true
  notify:
    - Systemd-networkd restart

- name: Setup wg0 network
  template:
    src: wireguard/network.j2
    dest: /etc/systemd/network/wg0.network
    owner: root
    group: systemd-network
    mode: "0o640"
  become: true
  notify:
    - Systemd-networkd restart

- name: Flush handlers
  meta: flush_handlers
