# - name: Does folder exist
#   local_action: stat path=~{{ ansible_facts.env.SUDO_USER }}/bin
#   register: folder

- name: Does folder exist
  delegate_to: localhost
  stat:
    path: "~{{ ansible_facts.env.SUDO_USER }}/bin"
  register: folder

- when: folder.stat.exists
  block:
    - name: Copy bin folder with owner and permission
      copy:
        src: ~/bin
        dest: /usr/local
        mode: "0o775"
    - name: Delete origin folder
      file:
        path: ~{{ ansible_facts.env.SUDO_USER }}/bin
        state: absent

- name: Generate bibiname script
  template:
    src: "bin/bibiname.j2"
    dest: "/usr/local/bin/bibiname"
    mode: "0o775"
