- when: flavor.ephemeral | int > 0
  block:
    - name: Ensure /vol/scratch exists
      file:
        path: /vol/scratch
        state: directory
        mode: "0777"

    - name: Mount ephemeral to /mnt cleanly
      mount:
        path: /mnt
        src: LABEL=ephemeral0
        fstype: ext4
        opts: defaults,nofail # ,_netdev
        state: mounted

    - name: Bind /vol/scratch to /mnt
      mount:
        path: /vol/scratch
        src: /mnt
        fstype: none
        opts: bind,nosuid,nodev
        state: mounted
