- name: Install NFS server package
  apt:
    name: "nfs-kernel-server"
    state: present

- name: Create shared directories
  file:
    path: "{{ item.src }}"
    state: directory
    owner: root
    group: root
    mode: "0o777"
  with_items:
    - "{{ nfs_shares }}"

- name: Configure nfs exports
  lineinfile:
    path: /etc/exports
    state: present
    regexp: '^{{ item.src }} '
    line: "{{ item.src }}
    {{cluster_cidrs|map(attribute='provider_cidrs')|flatten|join('(rw,nohide,insecure,no_subtree_check,async) ')}}\
    (rw,nohide,insecure,no_subtree_check,async)
    {{ '10.0.0.0/'+wireguard.mask_bits|default(24)|string + '(rw,nohide,insecure,no_subtree_check,async)'
    if wireguard is defined }}"
  with_items:
    - "{{ nfs_shares }}"
  notify:
    - Nfs-server
