- name: Ensure Keyring Directory
  file:
    group: root
    owner: root
    path: "/etc/apt/keyrings"
    state: "directory"
    mode: "755"

- name: Add Docker's Official GPG Key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    group: root
    owner: root
    dest: /etc/apt/keyrings/docker.asc
    mode: "644"

- name: Add docker repository to apt
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: true

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin


- name: Configure Docker
  copy:
    content: |-
      {
         "mtu": {{ ansible_default_ipv4.mtu }}
      }
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0o644"
  notify: Docker

- name: Create Docker Group and Change GID
  group:
    name: docker
    gid: 1234
    state: present

- name: Append Ubuntu User To Group Docker
  user:
    name: ubuntu
    append: true
    groups: docker

- name: Configure docker with nvidia-container-toolkit
  when: flavor.gres is defined
  command: nvidia-ctk runtime configure --runtime=docker
  notify: Docker
