# Slurm tasks for both master and worker

- name: Create Slurm group
  group:
    name: slurm
    gid: 64030

- name: Create Slurm user
  user:
    name: slurm
    uid: 64030
    group: slurm

# - name: Create pinning configuration for slurm-bibigrid version 23.11.*
#   copy:
#     content: |
#       Package: slurm-bibigrid
#       Pin: version 23.11.*
#       Pin-Priority: 1001
#     dest: /etc/apt/preferences.d/slurm-bibigrid
#     mode: "0o311"

- name: Install slurm-bibigrid package
  apt:
    name: "{{ slurm_conf.package.version }}"
    state: present
  when: not slurm_conf.package.use_experimental|default(false)|bool

- name: Download and install experimental slurm-bibigrid package
  apt:
    deb: "{{ slurm_conf.package.experimental_url }}"
    state: present
  when: slurm_conf.package.use_experimental|default(false)|bool

- name: Install Slurm package dependencies
  apt:
    name:
      - munge

- name: Configure MUNGE
  block:
    - name: Install MUNGE key
      copy:
        src: munge/munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: "0600"
      register: munge_key

    - name: Restart MUNGE after configuration
      systemd:
        name: munge
        state: restarted
      when: munge_key.changed


- name: Ensure Slurm directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    owner: root
    group: slurm
  loop:
    - /etc/slurm
    - /var/lib/slurm
    - /var/lib/slurm/slurmd
    - /var/log/slurm

- name: Create system overrides directory (slurmd)
  file:
    path: /etc/systemd/system/slurmd.service.d
    group: root
    owner: root
    mode: "0755"
    state: directory

- name: Configure slurmd for configless mode
  template:
    src: slurm/systemd/slurmd.override.j2
    dest: /etc/systemd/system/slurmd.service.d/override.conf
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart slurmd

# The controller owns the Slurm configuration in configless mode which means that copying slurm config files is omitted
# Slurmd is started after the master setup
