# Slurm tasks only executed on the on the master.
# The master is also a Slurm worker, so the common 042-slurm.yaml
# has already configured slurmd on this machine.

- name: Create Slurm user
  user:
    name: slurm
    uid: 64030
    group: slurm
    groups:
      - ansible # ensure that slurm user on master can use ansible playbook for on demand scheduling
    append: true
    home: /opt/slurm
    shell: /bin/false

- name: Create system overrides directory (slurmctld)
  file:
    path: "/etc/systemd/system/slurmctld.service.d"
    group: root
    owner: root
    mode: "0755"
    state: directory

- name: Copy system override (slurmctld)
  copy:
    src: "slurm/systemd/slurmctld.override"
    dest: "/etc/systemd/system/slurmctld.service.d/override.conf"
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart slurmctld

# ---------------------------------------------------------------------------
# SLURM CONFIGURATION
# ---------------------------------------------------------------------------
#
# In configless mode these files are authoritative on the controller.
# slurmd obtains the configuration from slurmctld.

- name: Create Slurm configuration
  template:
    src: slurm/slurm.j2
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: root
    mode: "0444"
    force: true
  notify:
    - Reconfigure slurmctld
  tags:
    - slurm-reconfigure

- name: Create Job Container configuration
  template:
    src: slurm/job_container.j2
    dest: /etc/slurm/job_container.conf
    owner: slurm
    group: root
    mode: "0444"
    force: true
  notify:
    - Restart slurmd

- name: Slurm cgroup configuration
  copy:
    src: slurm/cgroup.conf
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: root
    mode: "0444"
  notify:
    - Reconfigure slurmctld
  tags:
    - slurm-reconfigure

- name: Create Slurm GRES configuration
  template:
    src: slurm/gres.j2
    dest: /etc/slurm/gres.conf
    owner: slurm
    group: root
    mode: "0444"
    force: true
  notify:
    - Reconfigure slurmctld
  tags:
    - slurm-reconfigure

# ---------------------------------------------------------------------------
# OPENSTACK CREDENTIALS
# Slurm needs access to the credentials in order to schedule nodes on demand
# ---------------------------------------------------------------------------

- name: Change group ownership of OpenStack credentials file to slurm if it exists
  block:
    - name: Check if the OpenStack credentials file exists
      stat:
        path: /etc/openstack/clouds.yaml
      register: bibigrid_file_stat

    - name: Change group ownership of OpenStack credentials file to slurm
      file:
        path: /etc/openstack/clouds.yaml
        group: slurm
        mode: "0640"
      when: bibigrid_file_stat.stat.exists

# ---------------------------------------------------------------------------
# SLURM DATABASE
# ---------------------------------------------------------------------------

- name: Create slurm db
  mysql_db:
    name: "{{ slurm_conf.db }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create slurm db user
  mysql_user:
    name: "{{ slurm_conf.db_user }}"
    password: "{{ slurm_conf.db_password }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create slurmdb configuration file
  template:
    src: slurm/slurmdbd.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: root
    mode: "0600"
  notify:
    - Restart slurmdbd

# ---------------------------------------------------------------------------
# JWT
# ---------------------------------------------------------------------------

- name: Generate random JWT Secret
  command:
    cmd: "dd if=/dev/random of=/etc/slurm/jwt-secret.key bs=32 count=1"
    creates: "/etc/slurm/jwt-secret.key"

- name: Change file properties of JWT Secret file
  file:
    path: /etc/slurm/jwt-secret.key
    owner: slurm
    group: slurm
    mode: "0600"

# ---------------------------------------------------------------------------
# SLURM REST API
# ---------------------------------------------------------------------------

- name: Copy env file for configuration of slurmrestd
  copy:
    src: slurm/default/slurmrestd
    dest: /etc/default/slurmrestd
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart slurmrestd

- name: Create system overrides directories (slurmdbd/slurmrestd)
  file:
    path: "/etc/systemd/system/{{ item }}.service.d"
    group: root
    owner: root
    mode: "0755"
    state: directory
  loop:
    - slurmdbd
    - slurmrestd

- name: Copy system overrides (slurmdbd/slurmrestd)
  copy:
    src: "slurm/systemd/{{ item }}.override"
    dest: "/etc/systemd/system/{{ item }}.service.d/override.conf"
    mode: "0644"
    owner: root
    group: root
  loop:
    - slurmdbd
    - slurmrestd
  notify:
    - Restart slurmdbd
    - Restart slurmrestd

# ---------------------------------------------------------------------------
# SLURM USER / OPT SLURM
# ---------------------------------------------------------------------------

- name: Register Slurm users home dir
  shell: "set -o pipefail && grep slurm /etc/passwd | cut -d ':' -f 6"
  register: bibigrid_slurm_home
  changed_when: false
  args:
    executable: bash

- name: Change mode of /opt/slurm directory
  file:
    owner: slurm
    group: ansible
    path: /opt/slurm/
    state: directory
    mode: "0770"

- name: Ensure /etc/slurm dir exists
  file:
    path: /etc/slurm/
    state: directory
    mode: "0755"

- name: Ensure /opt/slurm/.ssh/ dir exists
  file:
    path: /opt/slurm/.ssh/
    group: slurm
    owner: slurm
    state: directory
    mode: "0700"

- name: Copy private key (openstack keypair)
  copy:
    src: ~/.ssh/id_ecdsa
    dest: /opt/slurm/.ssh/id_ecdsa
    owner: slurm
    group: slurm
    mode: "0600"

# ---------------------------------------------------------------------------
# ELASTIC / POWER MANAGEMENT
# ---------------------------------------------------------------------------

- name: Copy create program script (power)
  copy:
    src: slurm/resume.sh
    dest: /opt/slurm/resume.sh
    owner: slurm
    group: ansible
    mode: "0550"

- name: Copy terminate program script (power)
  copy:
    src: slurm/suspend.sh
    dest: /opt/slurm/suspend.sh
    owner: slurm
    group: ansible
    mode: "0550"

- name: Copy fail program script (power)
  copy:
    src: slurm/fail.sh
    dest: /opt/slurm/fail.sh
    owner: slurm
    group: ansible
    mode: "0550"

# ---------------------------------------------------------------------------
## OPENSTACK SERVER MANAGEMENT
# ---------------------------------------------------------------------------

- name: Copy "create_server.py" script
  copy:
    src: slurm/create_server.py
    dest: /usr/local/bin/create_server.py
    owner: slurm
    group: ansible
    mode: "0750"

- name: Copy "delete_server.py" script
  copy:
    src: slurm/delete_server.py
    dest: /usr/local/bin/delete_server.py
    owner: slurm
    group: ansible
    mode: "0750"

- name: Install python dependencies
  pip:
    name:
      - python-openstackclient==6.0.0
      - openstacksdk==0.62.0
      - os_client_config
      - filelock
      - paramiko
      - ansible-runner
      - pyzabbix
    virtualenv: /opt/bibigrid-venv

- name: Add default user to ansible group
  user:
    name: "{{ ssh_user }}"
    append: true
    groups:
      - ansible

# ---------------------------------------------------------------------------
# WORKER USERDATA
# ---------------------------------------------------------------------------

- name: Generate location specific worker userdata
  template:
    src: slurm/worker_userdata.j2
    dest: "/opt/slurm/userdata_{{ hostvars[item].cloud_identifier }}.txt"
    owner: slurm
    group: ansible
    mode: "0640"
  with_items: "{{ groups.vpngtw + groups.master }}"

# ---------------------------------------------------------------------------
# SERVICE STARTUP
# ---------------------------------------------------------------------------
#
#   1. slurmdbd
#   2. slurmctld
#   3. slurmrestd

- name: Enable and start slurmdbd
  systemd:
    name: slurmdbd
    enabled: true
    masked: false
    state: started
    daemon_reload: true

- name: Enable and start slurmctld
  systemd:
    name: slurmctld
    enabled: true
    masked: false
    state: started
    daemon_reload: true

- name: Enable and start slurmrestd
  systemd:
    name: slurmrestd
    enabled: true
    masked: false
    state: started
    daemon_reload: true
