- name: Generate directory structure available on all hosts
  file:
    path: /etc/bibigrid
    state: directory
    owner: root
    group: '{{ ansible_distribution | lower }}'
    mode: 0775

- file:
    path: /vol/
    state: directory
    owner: root
    group: '{{ ansible_distribution | lower }}'
    mode: 0775

- file:
    path: /vol/spool/
    state: directory
    mode: 0777

- file:
    path: /opt
    state: directory
    owner: root
    group: '{{ ansible_distribution | lower }}'
    mode: 0775

- name: Create link in '{{ ansible_distribution | lower }}' home
  file:
    src: /vol/
    dest: '/home/{{ ansible_distribution | lower }}/vol'
    state: link

