- name: Generate directory structure available on all hosts
  file:
    path: /etc/bibigrid
    state: directory
    owner: root
    group: ubuntu
    mode: 0775

- file:
    path: /vol/
    state: directory
    owner: root
    group: ubuntu
    mode: 0775

- file:
    path: /vol/spool/
    state: directory
    owner: root
    group: ubuntu
    mode: 0777

- file:
    path: /opt
    state: directory
    owner: root
    group: ubuntu
    mode: 0775

- name: Create link in ubuntu home
  file:
    src: /vol/
    dest: /home/ubuntu/vol
    state: link

