- name: Create SLURM configuration directory
  file:
    path: /etc/slurm-llnl
    state: directory
    owner: root
    group: root
    mode: 0755


- name: SLURM configuration
  template:
    src: slurm/slurm.conf
    dest: /etc/slurm-llnl/slurm.conf
    owner: root
    group: root
    mode: 0444
  register: slurm_conf


- name: SLURM cgroup configuration
  copy:
    src: slurm/cgroup.conf
    dest: /etc/slurm-llnl/cgroup.conf
    owner: root
    group: root
    mode: 0444
  register: slurm_cggroup_conf

- name: SLURM cgroup allowed devices conf
  copy:
    src: slurm/cgroup_allowed_devices_file.conf
    dest: /etc/slurm-llnl/cgroup_allowed_devices_file.conf
    owner: root
    group: root
    mode: 0444
  register: SLURM_cgroup_allowed_devices_conf