- name: Install Slurm base packages (includes slurmd, slurmctld, slurm-client)
  apt:
    name:
      - slurm-wlm
    state: latest

- name: SLURM configuration
  template:
    src: slurm/slurm.conf
    dest: /etc/slurm/slurm.conf
    owner: slurm
    group: root
    mode: 0444
  register: slurm_conf

- name: SLURM cgroup configuration
  copy:
    src: slurm/cgroup.conf
    dest: /etc/slurm/cgroup.conf
    owner: slurm
    group: root
    mode: 0444
  register: slurm_cgroup

- name: SLURM cgroup allowed devices conf
  copy:
    src: slurm/cgroup_allowed_devices_file.conf
    dest: /etc/slurm/cgroup_allowed_devices_file.conf
    owner: root
    group: root
    mode: 0444
  register: slurm_cgroup_allowed_devices

