# add apache2
- name: Install apache2
  apt:
    name: "apache2"
    state: present  # not using latest package to avoid time consuming checks for prepared images
  tags: ["master-apache2"]

- name: Install Ganglia
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ganglia-monitor
    - ganglia-webfrontend
    - gmetad
  tags: ["master-ganglia-install"]

- name: Configure Ganglia
  copy:
    src: ganglia/ganglia.conf
    dest: /etc/apache2/sites-available/ganglia.conf
    owner: root
    group: root
    mode: 0644
  tags: ["master-ganglia-configure"]

- copy:
    src: ganglia/gmetad.conf
    dest: /etc/ganglia/gmetad.conf
    owner: root
    group: root
    mode: 0644
  tags: ["master-ganglia-copy"]

- template:
    src: ganglia/gmond.conf.j2
    dest: /etc/ganglia/gmond.conf
    owner: root
    group: root
    mode: 0644
  tags: ["master-ganglia-template"]

- name: (Re-)start Ganglia
  systemd:
    name: ganglia-monitor
    state: restarted
    enabled: yes
  tags: ["master-ganglia-restart"]
    
- name: Enable Ganglia sites
  shell: "/usr/sbin/a2ensite ganglia"
  args:
    creates: /etc/apache2/sites-enabled/ganglia.conf
  register: ganglia_site_enabled
  tags: ["master-ganglia-site-enable"]
    
- name: (Re-)start Apache
  systemd:
    name: apache2
    state: restarted
    enabled: yes
  when: ganglia_site_enabled
  tags: ["master-restart apache"]



