# -------------------
# -- Zabbix Server --
# -------------------

- name: Debian based OS
  block:
    - name: Install database server
      apt:
        name: mariadb-server
        state: latest

    - name: Install zabbix server
      apt:
        name: zabbix-server-mysql
        state: latest
        update_cache: yes

  when: "ansible_distribution_file_variety == 'Debian' or ansible_distribution == 'Ubuntu'"

- name: REHL based OS
  block:
    - name: Install database server
      dnf:
        name: mariadb
        state: latest

    - name: Install zabbix server
      dnf:
        name: zabbix-server-mysql
        state: latest
  when: "ansible_distribution_file_variety == 'RedHat' "

- name: Install python modul 'PyMySQL'
  pip:
    name: PyMySQL

- name: Create zabbix database
  mysql_db:
    name: "{{ zabbix.db }}"
    encoding: 'utf8'
    state: present
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create zabbix database user
  mysql_user:
    name: "{{ zabbix.db_user }}"
    password: "{{ zabbix.db_password}}"
    priv: '{{ zabbix.db }}.*:ALL'
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Check if zabbix schema exists
  shell: "echo describe users | mysql --user={{ zabbix.db_user}} --password={{ zabbix.db_password }} zabbix"
  ignore_errors: True
  register: zabbix_schema_exists

- name: Import initial db schema
  shell: "zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql --user={{ zabbix.db_user}} --password={{ zabbix.db_password }} zabbix"
  when: zabbix_schema_exists.rc == 1

- name: Update Admin password
  shell: "echo \"update users set passwd=md5('{{ zabbix.admin_password }}') where alias='Admin'\" | mysql --user={{ zabbix.db_user}} --password={{ zabbix.db_password }} zabbix"

- name: Adjust zabbix server configuration
  template:
    src: zabbix/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf

- name: Restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted
    enabled: yes

# -------------------------
# -- Zabbix Web Frontend --
# -------------------------

- name: Zabbix Web Frontend related packages for Debian (Debian 10, Ubuntu 18.04 and Ubuntu 20.04) based OS
  block:
    - name: Install apache web server and php
      apt:
        name:
          - apache2
          - php
        state: latest

    - name: Install zabbix web frontend
      apt:
        name:
          - zabbix-frontend-php
          - zabbix-apache-conf
        state: latest
  when: "ansible_distribution_file_variety == 'Debian' and not ( ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial' )"


- name: Zabbix Web Frontend related packages for Ubuntu 16.04
  block:
    - name: Install apache web server and php 7.4
      apt:
        name:
          - apache2
          - php7.4
          - php7.4-bcmath
          - php7.4-gd
          - php7.4-json
          - php7.4-ldap
          - php7.4-mysql
          - php7.4-mbstring
          - php7.4-xml
          - libapache2-mod-php7.4
        state: latest

    - name: Install zabbix web frontend
      apt:
        name:
          - zabbix-frontend-php-deprecated
        state: latest

    - name: Copy zabbix apache conf
      copy:
        src: zabbix/zabbix.conf
        dest: /etc/apache2/conf-available/zabbix.conf
        owner: root
        group: root
        mode: 0644

    - name: Enable zabbix apache conf
      file:
        src: /etc/apache2/conf-available/zabbix.conf
        dest: /etc/apache2/conf-enabled/zabbix.conf
        owner: root
        group: root
        state: link
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'"

- name: Zabbix Web Frontend related packages for REHL based OS
  block:
    - name: Install apache web server
      dnf:
        name: apache2
        state: latest

    - name: Install zabbix web frontend
      dnf:
        name:
          - zabbix-frontend-php
          - zabbix-apache-conf
        state: latest
  when: "ansible_distribution_file_variety == 'RedHat'"

- name: Create Zabbix web dir (if not exists)
  file:
    path: /etc/zabbix/web
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Adjust zabbix web frontend configuration
  block:
    - template:
        src: zabbix/apache.conf.j2
        dest: /etc/zabbix/apache.conf
    - template:
        src: zabbix/zabbix.conf.php.j2
        dest: /etc/zabbix/web/zabbix.conf.php

- name: Restart apache web server
  systemd:
    name: apache2
    state: restarted
    enabled: yes

# --------------------------------------
# -- Add worker nodes as zabbix hosts --
# --------------------------------------

- name: Add all worker nodes as zabbix hosts
  zabbix_host:
    server_url:  "http://{{ master.ip }}/zabbix/"
    login_user: Admin
    login_password: "{{ zabbix.admin_password }}"
    host_name: "{{ item.hostname }}"
    visible_name : "{{ item.hostname }}"
    description : add by ansible
    status: enabled
    state: present
    host_groups:
      - 'Linux servers'
    link_templates:
      - 'Template OS Linux by Zabbix Agent' # new in Zabbix 4.4
    interfaces:
      - type: 1 # agent
        main: 1 # default
        ip: "{{ item.ip }}"
        useip: 1 # connect using host IP address
        dns: "{{ master.hostname }}"
        port: 10050
  with_items:
    - "{{ workers }}"
  tags: ["scale-up"]

# --------------------------------------
# -- Remove deleted worker nodes as zabbix hosts --
# --------------------------------------

- name: Remove deleted worker nodes as zabbix hosts
  zabbix_host:
    server_url:  "http://{{ master.ip }}/zabbix/"
    login_user: Admin
    login_password: "{{ zabbix.admin_password }}"
    host_name: "{{ item.hostname }}"
    visible_name: "{{ item.hostname }}"
    description: removed by ansible
    status: disabled
    state: absent
  with_items:
    - "{{ deletedWorkers }}"
  tags: ["scale-down"]