#- name: Install Apache
#  include_role:
#    name: geerlingguy.apache

- name: Install MySQL
  include_role:
    name: geerlingguy.mysql

- name: Install Zabbix-Server
  include_role:
    name: dj-wasabi.zabbix-server

- name: Install Zabbix-Web
  include_role:
    name: dj-wasabi.zabbix-web

- name: Install zabbix-api via PIP
  pip:
    name: zabbix-api

- name: Add all worker nodes as zabbix hosts
  zabbix_host:
    server_url:  "http://{{ master.ip }}"
    login_user: Admin
    login_password: zabbix
    host_name: "{{ item.hostname }}"
    visible_name : "{{ item.hostname }}"
    description : add by ansible
    status: enabled
    state: present
    host_groups:
      - 'Linux servers'
    link_templates:
      - 'Template OS Linux'
    interfaces:
      - type: 1 #agent
        main: 1 # default
        ip: "{{ item.ip }}"
        useip: 1 # connect using host IP address
        dns: "{{ master.hostname }}"
        port: 10050
  with_items:
    - "{{ slaves }}"