- name: Install Slurm database and RestAPI packages
  apt:
    name:
      - slurmdbd
      - slurmrestd
    state: latest

- name: Create slurmdb configuration file
  template:
    src: slurm/slurmdbd.conf
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    group: root
    mode: 0600
  notify:
    - slurmdbd

- name: Generate random JWT Secret
  command:
    cmd: "dd if=/dev/random of=/etc/slurm/jwt-secret.key bs=32 count=1"
    creates: "/etc/slurm/jwt-secret.key" # only run the command when file is not present

- name: Change file Properties of JWT Secret file
  file:
    path: /etc/slurm/jwt-secret.key
    owner: slurm
    group: slurm
    mode: 0600

- name: Copy env file for configuration of slurmrestd
  copy:
    src: slurm/slurmrestd_default
    dest: /etc/default/slurmrestd
    owner: root
    group: root
    mode: 0644
  notify:
    - slurmdbd
    - slurmrestd

- name: Create Service Directory
  file:
    path: /etc/systemd/system/slurmrestd.service.d
    group: root
    owner: root
    mode: 0755
    state: directory

- name: Copy systemd Service override file
  copy:
    src: slurm/slurmrestd_override.conf
    dest: /etc/systemd/system/slurmrestd.service.d/override.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - slurmrestd
